### ISSUE TITLE
bug time not running and answer not choice

### ISSUE THREAD

**Issue by thisfardi** [jrj-sys/full-stack-quiz#1]
![image](https://user-images.githubusercontent.com/38723240/156937915-1cb38036-3b96-4060-abbb-0720f5e92126.png)
and button next question not to choice, how to solve ? thanks

**Comment by jrj-sys** [comment]
@thisfardi will update tonight, have not pushed changes

**Comment by jrj-sys** [comment]
@thisfardi timer functionality has been added, as well as a score system.

to do: score saving functionality + correct/wrong answer display
